Repository tweepy/tweepy, pull requests merged in 2019-06, with the labels that each got.

#704 [docs] Lists can have 5,000 members
  docs/api.rst
Labels: Documentation

#886 handle scrub_geo, status_withheld and user_withheld streaming events
  tweepy/streaming.py
Labels: Improvement

#939 Added possibility to compare `eq` and `ne` between users, using the unique `id`s.
  tweepy/models.py
Labels: Improvement

#1227 Add tweepy.AppAuthHandler documentation
  docs/auth_tutorial.rst
Labels: Documentation

#1169 Added _json attribute to Models: List, Friendship and Category
  tweepy/models.py
Labels: Improvement, Need Follow-Up, Stale
