Repository tweepy/tweepy, pull requests merged in 2019-05, with the labels that each got.

#832 Use built in json library
  tweepy/parsers.py
  tweepy/streaming.py
  tweepy/utils.py
Labels: Improvement

#1208 Add cursor param to blocks_ids and mutes_ids
  docs/api.rst
  tweepy/api.py
Labels: Bug, Documentation, Improvement

#931 Change API.blocks_ids payload type to ids
  tweepy/api.py
Labels: Bug, Improvement

#904 Added missing return keyword
  tweepy/api.py
Labels: Improvement

#1090 Add a support of the 'perform_block' param for api.report_spam() method
  docs/api.rst
  tweepy/api.py
Labels: Improvement

#1215 Add API.mutes
  tweepy/api.py
Labels: Feature
