Repository tweepy/tweepy, pull requests merged in 2020-12, with the labels that each got.

#1458 Fixed issue #1410
  docs/api.rst
  tweepy/api.py
Labels: Documentation, Improvement

#1413 Fixes #1412
  tweepy/api.py
Labels: Bug

#1475 Allows media upload from BytesIO
  tweepy/api.py
Labels: Improvement, Need Follow-Up

#1444 fixed Issue #1443
  tweepy/models.py
Labels: Bug, Need Follow-Up

#1482 Drop support for Python 2
  .github/workflows/test.yml
  README.md
  docs/code_snippet.rst
  docs/conf.py
  examples/oauth.py
  examples/streaming.py
  setup.py
  tests/test_auth.py
  tests/test_cursors.py
  tests/test_resultset.py
  tests/test_streaming.py
  tox.ini
  tweepy/__init__.py
  tweepy/api.py
  tweepy/auth.py
  tweepy/binder.py
  tweepy/cache.py
  tweepy/cursor.py
  tweepy/error.py
  tweepy/models.py
  tweepy/parsers.py
  tweepy/streaming.py
  tweepy/utils.py
Labels: Improvement

#1414 Adds video upload
  cassettes/testmediauploadgif.yaml
  cassettes/testmediauploadpng.yaml
  cassettes/testvideoupload.yaml
  docs/api.rst
  examples/animated.gif
  examples/video.mp4
  tests/test_api.py
  tests/test_rate_limit.py
  tweepy/api.py
Labels: Feature, Improvement

#1484 Doc fix
  cassettes/testusertimeline.json
  docs/api.rst
  docs/parameters.rst
  tests/test_api.py
  tweepy/api.py
Labels: Documentation, Improvement

#1306 make User object hashable to allow use with sets
  tweepy/models.py
Labels: Improvement, Need Follow-Up
