Repository tweepy/tweepy, pull requests merged in 2020-07, with the labels that each got.

#1362 Correcting a very small typo in the docs :)
  docs/getting_started.rst
Labels: Documentation

#1338 Increase max image size for gif
  tweepy/api.py
Labels: Bug, Improvement

#1342 EHN: Save the raw JSON on DirectMessages as well.
  tweepy/models.py
Labels: Improvement

#1294 Add API.search_30_day and API.search_full_archive
  docs/api.rst
  tweepy/api.py
  tweepy/binder.py
  tweepy/cursor.py
  tweepy/models.py
  tweepy/parsers.py
Labels: API, Documentation, Feature
