Repository tweepy/tweepy, pull requests merged in 2021-05, with the labels that each got.

#1584 Remove async from filter and sample functions
  tweepy/asynchronous/streaming.py
Labels: Improvement

#1491 Support asynchronous streaming
  docs/asyncstream.rst
  docs/conf.py
  docs/index.rst
  docs/install.rst
  setup.py
  tweepy/asynchronous/__init__.py
  tweepy/asynchronous/streaming.py
Labels: Documentation, Feature, Improvement

#1597 Update documentation for API.rate_limit_status to be consistent with other docstrings
  tweepy/api.py
Labels: Documentation
